# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

generatorOptions:
  disableNameSuffixHash: true

resources:
- manager.yaml

secretGenerator:
- envs:
  - config.env
  name: config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: keppel.eu-de-1.cloud.sap/ccloud/disco
  newTag: latest
